from algorithms.arrays import *
import unittest

class TestSuite(unittest.TestCase):
    def test_dynamic_array(self):
        A = DynamicArray()
        self.assertEqual(str(A), '')
        A.append(1)
        A.append(2)
        self.assertEqual(str(A), '1 2')
        self.assertEqual(A.capacity, 2)
        A.append(3)
        self.assertEqual(str(A), '1 2 3')
        is_empty = True if len(A) == 0 else False
        self.assertEqual(is_empty, False)
        self.assertEqual(A[1], 2)
        A.push_left(4)
        self.assertEqual(str(A), '4 1 2 3')
        B = DynamicArray()
        B.push_left(1)
        self.assertEqual(str(B), '1')
        A.pop()
        B.pop()
        self.assertEqual(str(B), '')
        self.assertEqual(str(A), '4 1 2')
        A.insert_index(1, 2)
        self.assertEqual(str(A), '4 2 1 2')
        A.insert_index(0, 5)
        A.insert_index(4, 8)
        self.assertEqual('5 4 2 1 8 2', str(A))
        self.assertEqual(3, A.find_key(1))
        self.assertEqual(4, A.find_key(8))
        self.assertEqual(-1, A.find_key(10))
        A.append(2)
        A.remove_key(2)
        self.assertEqual(str(A), '5 4 1 8')
        A.append(5)
        A.remove_key(5)
        self.assertEqual(str(A), '4 1 8')
        A.delete_index(1)
        self.assertEqual(str(A), '4 8')